# library -----------------------------------------------------------------

library(tidyverse)
library(bbr)
library(here)
library(MASS)
library(bbr)
library(whisker)
library(PKPDmisc)
library(glue)
library(mvtnorm)
library(patchwork)
library(corrplot)

# read in data sets generated by sir -------------------------------------
sample_ofvs <- read.csv(here::here("data", "sir", "sir-106-sample-ofvs.csv"), header = TRUE)
sample_param <- read.csv(here::here("data", "sir", "sir-106-sample-param.csv"), header = TRUE)

# read in final model .ext file (param estimations)
ext <- read.table(file = here::here("model", "pk", "106", "106.ext"), 
                  skip = 1, 
                  header = TRUE) %>% 
  filter(ITERATION == max(ITERATION)) %>% # retain final estimates only
  dplyr::select(-ITERATION, -OBJ)         # remove iteration and obj columns

# read in final model .cov file (var-cov matrix)
cov <- read.table(file = here::here("model", "pk", "106", "106.cov"), 
                  skip = 1, 
                  header = TRUE) %>% 
  dplyr::select(-NAME)                    # remove param name column

param_names <- names(ext)

ext_matrix <- ext %>% data.matrix()            # convert ext to matrix
cov_matrix <- cov %>% data.matrix()            # convert cov to matrix

inf <- 1.25  # 1.25 fold inflation

cov_matrix_inf <- cov_matrix*inf   # convert cov to matrix (inflate by 1.25 fold)

# compute importance ratios -----------------------------------------------

# compute pdf of parameter vector
sample_ofvs <- sample_ofvs %>% mutate(pdf = dmvnorm(as.matrix(sample_param), mean = ext_matrix, sigma = cov_matrix_inf)) 

# extract final model ofv and parameter estimate pdf
final_mod <- read_model(.path = file.path("./model/pk", "106"))
final_mod_sum <- model_summary(final_mod)

sample_ofvs <-
  sample_ofvs %>%
  mutate(final_ofv = final_mod_sum$ofv[[1]]$ofv_no_constant,
         final_pdf = dmvnorm(ext_matrix, mean = ext_matrix, sigma = cov_matrix_inf))

# compute dofv, dofv_var, relpdf and important ratio (ir)
sample_ofvs <-
  sample_ofvs %>%
  mutate(dofv = ofv - final_ofv,
         relpdf = pdf/final_pdf) %>%
  mutate(dofv_var = exp(-0.5*dofv)) %>%
  mutate(ir = dofv_var/relpdf)

# resample ----------------------------------------------------------------

sample_ofvs <- sample_ofvs %>% mutate(prob = ir/sum(ir, na.rm = TRUE))   # compute resample probability based on importance ratios

M <- 1000

withr::with_seed(seed = 0720, 
                 sample_rows <- sample(x = na.omit(sample_ofvs)$nsim, 
                                       size = M, 
                                       replace = TRUE, 
                                       prob = na.omit(sample_ofvs)$prob)
)

resample_param <- sample_param[sample_rows, ]
resample_ofvs <- sample_ofvs[sample_rows, ]

map_lgl(resample_param, anyNA)
map_lgl(resample_ofvs, anyNA)

# output `resample_param` and `resample_ofvs`   --------------------------------------

# sir_output_dir <- here::here("data","sir")
# if(!dir.exists(sir_output_dir)) dir.create(sir_output_dir)
# 
# sir_sample   <- cbind(sample_ofvs, sample_param)
# sir_resample <- cbind(resample_ofvs, resample_param)
# 
# write.csv(sir_sample, file.path(sir_output_dir, "sir-106-sample.csv"), row.names = FALSE)
# write.csv(sir_resample, file.path(sir_output_dir, "sir-106-resample.csv"), row.names = FALSE)
# 
# sessionInfo()


############################################################################################

# graphical check ofvs ----------------------------------------------------

###### ofvs sample visualization

# visualize the distribution of importance ratio (expected to be centered around 1.0)
p1 <- sample_ofvs %>% ggplot()+
  geom_boxplot(aes(y = ir))+
  scale_y_log10()+
  geom_hline(yintercept = 1, color = "red", linetype = 2)+
  theme_bw()+
  ylab("Importance Ratio")

# visualize dofv ~ relpdf 
p2 <- sample_ofvs %>% ggplot()+
  geom_point(aes(x= dofv_var, y = relpdf))+
  scale_y_log10()+
  scale_x_log10()+
  geom_abline(slope = 1, intercept = 0, color = "red", linetype = 2)+
  theme_bw()+
  xlab("exp(-0.5 * dOFV)")+
  ylab("Relative pdf")

###### ofvs resample visualization

# visualize the distribution of importance ratio (expected to be centered around 1.0)
p3 <- resample_ofvs %>% ggplot()+
  geom_boxplot(aes(y = ir))+
  scale_y_log10()+
  geom_hline(yintercept = 1, color = "red", linetype = 2)+
  theme_bw()+
  ylab("Importance Ratio")

# visualize dofv ~ relpdf 
p4 <- resample_ofvs %>% ggplot()+
  geom_point(aes(x= dofv_var, y = relpdf))+
  scale_y_log10()+
  scale_x_log10()+
  geom_abline(slope = 1, intercept = 0, color = "red", linetype = 2)+
  theme_bw()+
  xlab("exp(-0.5 * dOFV)")+
  ylab("Relative pdf")

##### combine plots

p1 + p2 + p3 + p4 + plot_layout(ncol = 2)

# compute 95% ci of parameter estimates -----------------------------------

# SIR 95% CI
sir <- 
  t(resample_param) %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "parameter") %>% 
  rowwise() %>% 
  mutate(sir_median = median(c_across(!parameter)),  
         sir_lower = quantile(c_across(!parameter), 0.025), 
         sir_upper = quantile(c_across(!parameter), 0.975)) %>% 
  ungroup() %>% 
  mutate(type = "SIR") %>% 
  dplyr::select(parameter, sir_median, sir_lower, sir_upper, type) 

# 95% CI based on var-cov matrix (symmetrical)
final_est <- 
  data.frame(final_est = t(ext_matrix), 
             final_se = sqrt(diag(cov_matrix))) %>% 
  mutate(final_lower = final_est - 1.96*final_se, 
         final_upper = final_est + 1.96*final_se) %>% 
  rownames_to_column(var = "parameter") %>% 
  mutate(parameter = str_replace_all(parameter, "\\.", "\\")) %>% 
  mutate(type = "COV") %>% 
  dplyr::select(parameter, final_est, final_lower, final_upper, type) 

# Bootstrap 95% CI
boot <-
  read_csv(here::here("data", "boot", "boot-106.csv")) %>%
  dplyr::select(-run) %>%
  as.matrix() %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var = "parameter") %>%
  mutate(parameter = str_replace_all(parameter, "\\,", "\\")) %>%
  mutate(parameter = str_replace_all(parameter, "\\(", "\\")) %>%
  mutate(parameter = str_replace_all(parameter, "\\)", "\\")) %>%
  rowwise() %>%
  mutate(boot_median = median(c_across(!parameter)),
         boot_lower = quantile(c_across(!parameter), 0.025),
         boot_upper = quantile(c_across(!parameter), 0.975)) %>%
  ungroup() %>%
  mutate(type = "BS") %>%
  dplyr::select(parameter, boot_median, boot_lower, boot_upper, type)

# Bayes 95% CI

bayes_1 <- read.table(here::here("model", "pk", "201", "201.ext"), skip = 1, header = TRUE)
bayes_2 <- read.table(here::here("model", "pk", "202", "202.ext"), skip = 1, header = TRUE)
bayes_3 <- read.table(here::here("model", "pk", "203", "203.ext"), skip = 1, header = TRUE)
bayes_4 <- read.table(here::here("model", "pk", "204", "204.ext"), skip = 1, header = TRUE)

bayes <- 
  bind_rows(bayes_1, bayes_2, bayes_3, bayes_4) %>% 
  filter(ITERATION > 0) %>% 
  dplyr::select(-ITERATION, -MCMCOBJ) %>% 
  as.matrix() %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var = "parameter") %>%
  mutate(parameter = str_replace_all(parameter, "\\.", "\\")) %>% 
  rowwise() %>%
  mutate(bayes_median = median(c_across(!parameter)),
         bayes_lower = quantile(c_across(!parameter), 0.025),
         bayes_upper = quantile(c_across(!parameter), 0.975)) %>%
  ungroup() %>%
  mutate(type = "BAY") %>%
  dplyr::select(parameter, bayes_median, bayes_lower, bayes_upper, type)

# side to side comparison plot
ggplot()+
  geom_point(data = sir, aes(x=type, y=sir_median))+
  geom_point(data = final_est, aes(x=type, y=final_est))+
  geom_point(data = boot, aes(x=type, y=boot_median))+
  geom_point(data = bayes, aes(x=type, y=bayes_median))+
  geom_errorbar(data = sir, aes(x=type, ymin=sir_lower, ymax=sir_upper), width = 0.25)+
  geom_errorbar(data = final_est, aes(x=type, ymin=final_lower, ymax=final_upper), width = 0.25)+
  geom_errorbar(data = boot, aes(x=type, ymin=boot_lower, ymax=boot_upper), width = 0.25)+
  geom_errorbar(data = bayes, aes(x=type, ymin=bayes_lower, ymax=bayes_upper), width = 0.25)+
  theme_bw()+
  facet_wrap(~parameter, scales = "free")+
  xlab("")+
  ylab("95% CIs")


# dOFV plots --------------------------------------------------------------

sample_ofvs_p <- 
  sample_ofvs %>% 
  filter(!is.na(dofv)) %>% 
  arrange(dofv) %>% 
  mutate(p = seq(from = 0, to = 1, length.out = n())) %>% 
  mutate(df = round(mean(.$dofv), digits = 1))

resample_ofvs_p <- 
  resample_ofvs %>% 
  filter(!is.na(dofv)) %>% 
  arrange(dofv) %>% 
  mutate(p = seq(from = 0, to = 1, length.out = n()))%>% 
  mutate(df = round(mean(.$dofv), digits = 1))


chisq_ofvs_p <- 
  data.frame(dofv = seq(min(sample_ofvs_p$dofv), max(sample_ofvs_p$dofv), length.out = 1000)) %>% 
  mutate(p = pchisq(q = dofv, df = ncol(sample_param))) %>% 
  mutate(df = ncol(sample_param))

ggplot()+
  geom_line(data = sample_ofvs_p, aes(x=p, y=dofv), linetype = 2, col = "red")+
  geom_text(data = sample_ofvs_p, aes(x=0.75, y=50, label=paste0("proposal df", df)), col = "red")+
  geom_line(data = resample_ofvs_p, aes(x=p, y=dofv), col = "red")+
  geom_text(data = resample_ofvs_p, aes(x=0.75, y=40, label=paste0("sir df", df)), col = "red")+
  geom_line(data = chisq_ofvs_p, aes(x=p, y=dofv), col = "gray20")+
  geom_text(data = chisq_ofvs_p, aes(x=0.75, y=45, label=paste0("ref df", df)), col = "gray20")+
  theme_bw()

# var-cov matrix visualization --------------------------------------------

# proposal matrix
cov_proposal <- stats::var(sample_param) %>% as.matrix()
cor_proposal <- stats::cov2cor(cov_proposal) %>% as.matrix()
var_proposal <- diag(cov_proposal)

cor_proposal %>% corrplot::corrplot(method = "color")

# sir matrix
cov_sir <- stats::var(resample_param) %>% as.matrix()
cor_sir <- stats::cov2cor(cov_sir) %>% as.matrix()
var_sir <- diag(cov_sir)

cor_sir %>% corrplot::corrplot(method = "color")
  






