# library -----------------------------------------------------------------

library(tidyverse)
library(here)

# read in data sets generated by sir -------------------------------------
sir_sample <- read.csv(here::here("data", "sir_output", "sir-sample-106.csv"), 
                       header = TRUE) %>% 
  mutate(nsim = 1:n())

# sir output folder
sir_output_dir <- here::here("data","sir_output")

# resample method 1 ------------------------------------------------------

# compute resample probability based on importance ratios (WEIGHT)
sir_sample_1 <- sir_sample %>% 
  mutate(prob = WEIGHT/sum(WEIGHT, na.rm = TRUE)) 

# resample
M <- 100

withr::with_seed(seed = 0720, 
                 sample_rows <- sample(x = na.omit(sir_sample_1)$nsim, 
                                       size = M, 
                                       replace = TRUE, 
                                       prob = na.omit(sir_sample_1)$prob)
)

sir_resample_1 <- sir_sample_1[sample_rows, ] %>% 
  dplyr::select(-nsim, -prob)

map_lgl(sir_resample_1, anyNA)

# output 
write.csv(sir_resample_1, 
          file.path(sir_output_dir, "sir-resample-106-1.csv"), 
          row.names = FALSE)

# resample method 2 -------------------------------------------------------

# reference: NONMEM user guide Introduction 7
# page 206

# read in final estimate and cov matrix for computing WEIGHT (based on final estimates)

w_denom <- mean(sir_sample$WEIGHT) # WEIGHT: aver weight across all sir samples
# from Intro to NM 7: "The weighted average parameter values are listed on the line labeled iteration -1000000000"
n_denom <- sir_sample %>% select(nsim) %>% max() # number of SIR sample

# resample (unsure how to specify number of resample with this method???)
withr::with_seed(seed = 0720, 
  sir_resample_2 <- 
    sir_sample %>%
    mutate(
      w_num = cumsum(WEIGHT), 
      prob = w_num / ((n_denom + 1) * w_denom)
    ) %>% 
    mutate(r = runif(n = n(), min = 0, max = 1)) %>% # random variable r sample from a uniform distribution
    mutate(sample_flag = ifelse(prob >= r, 1, 0)) %>%  # create a sample flag if prob >= r
    filter(sample_flag == 1) %>% 
    dplyr::select(-nsim, -w_num, -prob, -r, -sample_flag)
)
         
# output
write.csv(sir_resample_2, 
          file.path(sir_output_dir, "sir-resample-106-2.csv"), 
          row.names = FALSE)
  






