# library -----------------------------------------------------------------

library(tidyverse)
library(here)
library(bbr)
library(glue)


# dir ---------------------------------------------------------------------

modelDir <- here("model/pk")
runno <- "001b"
sirrunno <- "001b-sir"

# read in data sets generated by sir -------------------------------------
sirsample0 <- read.table(file.path(modelDir, sirrunno, glue("{sirrunno}.ext")), skip = 1, header = TRUE) 

sirsample1 <- sirsample0 %>% 
  mutate(dOFV = OBJ - OBJ[ITERATION == 0]) %>% 
  filter(ITERATION > 0)

# number of parameters in the original model
mod <- bbr::read_model(file.path(modelDir, runno))
nparam <- mod %>% model_summary() %>% param_estimates() %>% filter(fixed == FALSE) %>% nrow()

# resample method 1 ------------------------------------------------------

# compute resample probability based on importance ratios (WEIGHT)
sirsample1 <- sirsample1 %>% 
  mutate(prob = WEIGHT/sum(WEIGHT, na.rm = TRUE)) 

# resample
M1 <- 1000

withr::with_seed(seed = 0720, 
                 sample_rows <- sample(x = sirsample1$ITERATION, 
                                       size = M1, 
                                       replace = TRUE, 
                                       prob = sirsample1$prob)
)

sirresample1 <- sirsample1[sample_rows, ]

map_lgl(sirresample1, anyNA)

# resample method 2 -------------------------------------------------------

M2 <- 1000

sirinput <- glue("{modelDir}/{sirrunno}/{sirrunno}.ext")
siroutput <- glue("{modelDir}/{sirrunno}/{sirrunno}-rs.ext")

system(glue('/opt/NONMEM/nm75/util/table_resample {sirinput} {siroutput} s {M2} 0720'))

sirresample2 <- read.table(siroutput, skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0)


# dOFV plot (two method comparison) ---------------------------------------

sirresample1 <- sirresample1 %>% mutate(df = round(mean(dOFV), digits = 2))
sirresample2 <- sirresample2 %>% mutate(df = round(mean(dOFV), digits = 2))

ggplot()+
  stat_ecdf(data = sirresample1, aes(x = dOFV), color = "red")+
  stat_ecdf(data = sirresample2, aes(x = dOFV), color = "blue")+
  geom_text(data = distinct(sirresample1, df), aes(x = 20, y = 0.25, label = glue("SIR df using method 1: {df}")), color = "red")+
  geom_text(data = distinct(sirresample2, df), aes(x = 22.5, y = 0.25, label = glue("SIR df using method 2: {df}")), color = "blue")+
  ylab("Cumulative probablity")+
  theme_bw()+
  coord_flip()


# dOFV final --------------------------------------------------------------

dofv_dt <- bind_rows(sirsample1 %>% dplyr::select(-WEIGHT, -prob) %>% mutate(df = round(mean(dOFV), digits = 2), type = "Proposal"), 
                     sirresample2 %>% mutate(type = "SIR"))

ggplot()+
  stat_ecdf(data = dofv_dt, aes(x = dOFV, group = type, color = type))+
  stat_function(fun = pchisq, args = list(df = nparam), color = "gray20", linetype = 2)+
  geom_text(data = distinct(dofv_dt, df, .keep_all = TRUE), 
            aes(x = c(45, 40), y = 0.25, label = glue("Estimated df: {df}"), color = type))+
  geom_text(aes(x = 42.5, y = 0.25), label = glue("Theoretical Chi-Squared Distribution with {nparam} df"), color = "gray20")+
  theme_bw() + 
  ylab("Cumulative probablity")+
  coord_flip()+
  theme(legend.title = element_blank(), 
        legend.position = "bottom")
  
# glue("Theoretical Chi-Squared Distribution with {nparam} df")

# dOFV SIRDF sens ---------------------------------------------------------

# we will use NONMEM resampling method for the downstream analysis

sens1_dir <- file.path(modelDir, glue("{sirrunno}-sirdf"))

# resampling using NONMEM
# system(glue('/opt/NONMEM/nm75/util/table_resample {sens1_dir}/{sirrunno}-1/{sirrunno}-1.ext {sens1_dir}/{sirrunno}-1/{sirrunno}-1-rs.ext s {M2} 0720'))
# system(glue('/opt/NONMEM/nm75/util/table_resample {sens1_dir}/{sirrunno}-2/{sirrunno}-2.ext {sens1_dir}/{sirrunno}-2/{sirrunno}-2-rs.ext s {M2} 0720'))
# system(glue('/opt/NONMEM/nm75/util/table_resample {sens1_dir}/{sirrunno}-3/{sirrunno}-3.ext {sens1_dir}/{sirrunno}-3/{sirrunno}-3-rs.ext s {M2} 0720'))
# system(glue('/opt/NONMEM/nm75/util/table_resample {sens1_dir}/{sirrunno}-4/{sirrunno}-4.ext {sens1_dir}/{sirrunno}-4/{sirrunno}-4-rs.ext s {M2} 0720'))

sirsample_sens1_0 <- sirsample1 %>% mutate(SIRDF = 0, df = round(mean(dOFV), digits = 2)) %>% dplyr::select(-prob)

sirsample_sens1_1 <- read.table(glue("{sens1_dir}/{sirrunno}-1/{sirrunno}-1.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(SIRDF = 2, df = round(mean(dOFV), digits = 2))

sirsample_sens1_2 <- read.table(glue("{sens1_dir}/{sirrunno}-2/{sirrunno}-2.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(SIRDF = 4, df = round(mean(dOFV), digits = 2))

sirsample_sens1_3 <- read.table(glue("{sens1_dir}/{sirrunno}-3/{sirrunno}-3.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(SIRDF = 6, df = round(mean(dOFV), digits = 2))

sirsample_sens1_4 <- read.table(glue("{sens1_dir}/{sirrunno}-4/{sirrunno}-4.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(SIRDF = 8, df = round(mean(dOFV), digits = 2))

sirsample_sens1 <- bind_rows(sirsample_sens1_0, 
                             sirsample_sens1_4, 
                             sirsample_sens1_3,
                             sirsample_sens1_2, 
                             sirsample_sens1_1) %>% 
  mutate(SIRDF = as.factor(SIRDF)) %>% 
  mutate(df = glue("Estimated df: {df}"))

ggplot(sirsample_sens1)+
  stat_ecdf(aes(x = dOFV, group = SIRDF, color = SIRDF))+
  stat_function(fun = pchisq, args = list(df = nparam), linetype = 2)+
  geom_text(data = distinct(sirsample_sens1, SIRDF, .keep_all = TRUE), 
            aes(x = seq(20, 36, 4), y = 0.25, label = df, color = SIRDF))+
  geom_text(aes(x = 16, y = 0.25), label = glue("Theoretical Chi-Squared Distribution with {nparam} df"), color = "gray20")+
  theme_bw()+
  ylab("Cumulative probablity")+
  coord_flip()+
  theme(legend.position = "bottom")


# dOFV IACCEPT sens -------------------------------------------------------

# we will use NONMEM resampling method for the downstream analysis

sens3_dir <- file.path(modelDir, glue("{sirrunno}-iaccept"))

# # resampling using NONMEM
# system(glue('/opt/NONMEM/nm75/util/table_resample {sens3_dir}/{sirrunno}-1/{sirrunno}-1.ext {sens3_dir}/{sirrunno}-1/{sirrunno}-1-rs.ext s {M2} 0720'))
# system(glue('/opt/NONMEM/nm75/util/table_resample {sens3_dir}/{sirrunno}-2/{sirrunno}-2.ext {sens3_dir}/{sirrunno}-2/{sirrunno}-2-rs.ext s {M2} 0720'))
# system(glue('/opt/NONMEM/nm75/util/table_resample {sens3_dir}/{sirrunno}-3/{sirrunno}-3.ext {sens3_dir}/{sirrunno}-3/{sirrunno}-3-rs.ext s {M2} 0720'))
# system(glue('/opt/NONMEM/nm75/util/table_resample {sens3_dir}/{sirrunno}-4/{sirrunno}-4.ext {sens3_dir}/{sirrunno}-4/{sirrunno}-4-rs.ext s {M2} 0720'))

sirsample_sens3_0 <- sirsample1 %>% mutate(IACCEPT = 1, df = round(mean(dOFV), digits = 2)) %>% dplyr::select(-prob)

sirsample_sens3_1 <- read.table(glue("{sens3_dir}/{sirrunno}-1/{sirrunno}-1.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(IACCEPT = 0.2, df = round(mean(dOFV), digits = 2))

sirsample_sens3_2 <- read.table(glue("{sens3_dir}/{sirrunno}-2/{sirrunno}-2.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(IACCEPT = 0.4, df = round(mean(dOFV), digits = 2))

sirsample_sens3_3 <- read.table(glue("{sens3_dir}/{sirrunno}-3/{sirrunno}-3.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(IACCEPT = 0.6, df = round(mean(dOFV), digits = 2))

sirsample_sens3_4 <- read.table(glue("{sens3_dir}/{sirrunno}-4/{sirrunno}-4.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(IACCEPT = 0.8, df = round(mean(dOFV), digits = 2))

sirsample_sens3 <- bind_rows(sirsample_sens3_0, 
                             sirsample_sens3_4, 
                             sirsample_sens3_3,
                             sirsample_sens3_2, 
                             sirsample_sens3_1) %>% 
  mutate(IACCEPT = as.factor(IACCEPT)) %>% 
  mutate(df = glue("Estimated df: {df}"))

ggplot(sirsample_sens3)+
  stat_ecdf(aes(x = dOFV, group = IACCEPT, color = IACCEPT))+
  stat_function(fun = pchisq, args = list(df = nparam), linetype = 2)+
  geom_text(data = distinct(sirsample_sens3, IACCEPT, .keep_all = TRUE), 
            aes(x = seq(20, 36, 4), y = 0.25, label = df, color = IACCEPT))+
  geom_text(aes(x = 16, y = 0.25), label = glue("Theoretical Chi-Squared Distribution with {nparam} df"), color = "gray20")+
  theme_bw()+
  ylab("Cumulative probablity")+
  coord_flip()+
  theme(legend.position = "bottom")


# dOFV m/M ratio sens -----------------------------------------------------

# resampling using NONMEM
# taking sirdf = 4 as an example
# five tested ratio: 1,2,5,10,20

sens2_dir <- file.path(modelDir, glue("{sirrunno}-mmratio"))

# resampling using NONMEM
system(glue('/opt/NONMEM/nm75/util/table_resample {sens2_dir}/{sirrunno}-1/{sirrunno}-1.ext {sens2_dir}/{sirrunno}-1/{sirrunno}-1-rs.ext s {M2} -0720'))
system(glue('/opt/NONMEM/nm75/util/table_resample {sens2_dir}/{sirrunno}-2/{sirrunno}-2.ext {sens2_dir}/{sirrunno}-2/{sirrunno}-2-rs.ext s {M2} -0720'))
system(glue('/opt/NONMEM/nm75/util/table_resample {sens2_dir}/{sirrunno}-3/{sirrunno}-3.ext {sens2_dir}/{sirrunno}-3/{sirrunno}-3-rs.ext s {M2} -0720'))
system(glue('/opt/NONMEM/nm75/util/table_resample {sens2_dir}/{sirrunno}-4/{sirrunno}-4.ext {sens2_dir}/{sirrunno}-4/{sirrunno}-4-rs.ext s {M2} -0720'))
system(glue('/opt/NONMEM/nm75/util/table_resample {sens2_dir}/{sirrunno}-5/{sirrunno}-5.ext {sens2_dir}/{sirrunno}-5/{sirrunno}-5-rs.ext s {M2} -0720'))

sirresample_sens2_1 <- read.table(glue("{sens2_dir}/{sirrunno}-1/{sirrunno}-1-rs.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(`m/M ratio` = 1, df = round(mean(dOFV), digits = 2))

sirresample_sens2_2 <- read.table(glue("{sens2_dir}/{sirrunno}-2/{sirrunno}-2-rs.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(`m/M ratio` = 2, df = round(mean(dOFV), digits = 2))

sirresample_sens2_3 <- read.table(glue("{sens2_dir}/{sirrunno}-3/{sirrunno}-3-rs.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(`m/M ratio` = 5, df = round(mean(dOFV), digits = 2))

sirresample_sens2_4 <- read.table(glue("{sens2_dir}/{sirrunno}-4/{sirrunno}-4-rs.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(`m/M ratio` = 10, df = round(mean(dOFV), digits = 2))

sirresample_sens2_5 <- read.table(glue("{sens2_dir}/{sirrunno}-5/{sirrunno}-5-rs.ext"), skip = 1, header = TRUE) %>%
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>%
  filter(ITERATION > 0) %>%
  mutate(`m/M ratio` = 20, df = round(mean(dOFV), digits = 2))

sirresample_sens2 <- bind_rows(sirresample_sens2_1, 
                               sirresample_sens2_2, 
                               sirresample_sens2_3, 
                               sirresample_sens2_4, 
                               sirresample_sens2_5) %>% 
  mutate(`m/M ratio` = as.factor(`m/M ratio`)) %>% 
  mutate(df = glue("Estimated df: {df}"))

ggplot(sirresample_sens2)+
  stat_ecdf(aes(x = dOFV, group = `m/M ratio`, color = `m/M ratio`))+
  stat_function(fun = pchisq, args = list(df = nparam), linetype = 2)+
  geom_text(data = distinct(sirresample_sens2, `m/M ratio`, .keep_all = TRUE), 
            aes(x = seq(29.6, 20, -2.4), y = 0.25, label = df, color = `m/M ratio`))+
  geom_text(aes(x = 32, y = 0.25), label = glue("Theoretical Chi-Squared Distribution with {nparam} df"), color = "gray20")+
  theme_bw()+
  coord_flip()


















