# library -----------------------------------------------------------------

library(tidyverse)
library(here)
library(bbr)
library(glue)


# dir ---------------------------------------------------------------------

modelDir <- here("model/pk")
runno <- "106"
sirrunno <- "106-sir"

# read in data sets generated by sir -------------------------------------
sirsample0 <- read.table(file.path(modelDir, sirrunno, glue("{sirrunno}.ext")), skip = 1, header = TRUE) 

sirsample1 <- sirsample0 %>% 
  mutate(dOFV = OBJ - OBJ[ITERATION == 0]) %>% 
  filter(ITERATION > 0)

# number of parameters in the original model
mod <- bbr::read_model(file.path(modelDir, runno))
nparam <- mod %>% model_summary() %>% param_estimates() %>% filter(fixed == FALSE) %>% nrow()

# resample method 1 ------------------------------------------------------

# compute resample probability based on importance ratios (WEIGHT)
sirsample1 <- sirsample1 %>% 
  mutate(prob = WEIGHT/sum(WEIGHT, na.rm = TRUE)) 

# resample
M1 <- 1000

withr::with_seed(seed = 0720, 
                 sample_rows <- sample(x = sirsample1$ITERATION, 
                                       size = M1, 
                                       replace = TRUE, 
                                       prob = sirsample1$prob)
)

sirresample1 <- sirsample1[sample_rows, ]

map_lgl(sirresample1, anyNA)

# resample method 2 -------------------------------------------------------

M2 <- 1000

sirinput <- glue("{modelDir}/{sirrunno}/{sirrunno}.ext")
siroutput <- glue("{modelDir}/{sirrunno}/{sirrunno}-rs.ext")

system(glue('/opt/NONMEM/nm75/util/table_resample {sirinput} {siroutput} s {M2} 0720'))

sirresample2 <- read.table(siroutput, skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0)


# dOFV plot (two method comparison) ---------------------------------------

sirresample1 <- sirresample1 %>% mutate(df = round(mean(dOFV), digits = 2))
sirresample2 <- sirresample2 %>% mutate(df = round(mean(dOFV), digits = 2))

ggplot()+
  stat_ecdf(data = sirresample1, aes(x = dOFV), color = "red")+
  stat_ecdf(data = sirresample2, aes(x = dOFV), color = "blue")+
  geom_text(data = distinct(sirresample1, df), aes(x = 20, y = 0.25, label = glue("SIR df using method 1: {df}")), color = "red")+
  geom_text(data = distinct(sirresample2, df), aes(x = 25, y = 0.25, label = glue("SIR df using method 2: {df}")), color = "blue")+
  ylab("Cumulative probablity")+
  theme_bw()+
  coord_flip()
  

# dOFV SIRDF sens ---------------------------------------------------------

# we will use NONMEM resampling method for the downstream analysis

sens1_dir <- file.path(modelDir, glue("{sirrunno}-sirdf"))

# resampling using NONMEM
# system(glue('/opt/NONMEM/nm75/util/table_resample {sens1_dir}/{sirrunno}-1/{sirrunno}-1.ext {sens1_dir}/{sirrunno}-1/{sirrunno}-1-rs.ext s {M2} 0720'))
# system(glue('/opt/NONMEM/nm75/util/table_resample {sens1_dir}/{sirrunno}-2/{sirrunno}-2.ext {sens1_dir}/{sirrunno}-2/{sirrunno}-2-rs.ext s {M2} 0720'))
# system(glue('/opt/NONMEM/nm75/util/table_resample {sens1_dir}/{sirrunno}-3/{sirrunno}-3.ext {sens1_dir}/{sirrunno}-3/{sirrunno}-3-rs.ext s {M2} 0720'))
# system(glue('/opt/NONMEM/nm75/util/table_resample {sens1_dir}/{sirrunno}-4/{sirrunno}-4.ext {sens1_dir}/{sirrunno}-4/{sirrunno}-4-rs.ext s {M2} 0720'))

sirsample_sens1_0 <- sirsample1 %>% mutate(sirdf = 0, df = round(mean(dOFV), digits = 2)) %>% dplyr::select(-prob)

sirsample_sens1_1 <- read.table(glue("{sens1_dir}/{sirrunno}-1/{sirrunno}-1.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(sirdf = 2, df = round(mean(dOFV), digits = 2))

sirsample_sens1_2 <- read.table(glue("{sens1_dir}/{sirrunno}-2/{sirrunno}-2.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(sirdf = 4, df = round(mean(dOFV), digits = 2))

sirsample_sens1_3 <- read.table(glue("{sens1_dir}/{sirrunno}-3/{sirrunno}-3.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(sirdf = 6, df = round(mean(dOFV), digits = 2))

sirsample_sens1_4 <- read.table(glue("{sens1_dir}/{sirrunno}-4/{sirrunno}-4.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(sirdf = 8, df = round(mean(dOFV), digits = 2))

sirsample_sens1 <- bind_rows(sirsample_sens1_0, 
                             sirsample_sens1_1, 
                             sirsample_sens1_2, 
                             sirsample_sens1_3, 
                             sirsample_sens1_4) %>% 
  mutate(sirdf = as.factor(sirdf))

ggplot(sirsample_sens1)+
  stat_ecdf(aes(x = dOFV, group = sirdf, color = sirdf))+
  stat_function(fun = pchisq, args = list(df = nparam), linetype = 2)+
  geom_text(data = distinct(sirsample_sens1, sirdf, .keep_all = TRUE), 
            aes(x = seq(20, 36, 4), y = 0.25, label = df, color = sirdf))+
  theme_bw()+
  coord_flip()













