# library -----------------------------------------------------------------

library(tidyverse)
library(here)
library(bbr)
library(glue)


# dir ---------------------------------------------------------------------

modelDir <- here("model/pk")
runno <- "001b"
sirrunno <- "001b-sir"

# read in data sets generated by sir -------------------------------------
sirsample0 <- read.table(file.path(modelDir, sirrunno, glue("{sirrunno}.ext")), skip = 1, header = TRUE) 

sirsample1 <- sirsample0 %>% 
  mutate(dOFV = OBJ - OBJ[ITERATION == 0]) %>% 
  filter(ITERATION > 0)

names(sirsample1) <- gsub("\\.", "\\", names(sirsample1))

m <- sirsample1 %>% nrow() # number of sampling

# number of parameters in the original model
mod <- bbr::read_model(file.path(modelDir, runno))
nparam <- mod %>% model_summary() %>% param_estimates() %>% filter(fixed == FALSE) %>% nrow()

param_names <- mod %>% model_summary() %>% param_estimates() %>% filter(fixed == FALSE) %>% 
  mutate(parameter_names = str_replace_all(parameter_names, "\\(", "\\")) %>% 
  mutate(parameter_names = str_replace_all(parameter_names, "\\)", "\\")) %>% 
  mutate(parameter_names = str_replace_all(parameter_names, "\\,", "\\")) %>% 
  pull(parameter_names)

# resample method 1 ------------------------------------------------------

# compute resample probability based on importance ratios (WEIGHT)
sirsample1 <- sirsample1 %>% 
  mutate(prob = WEIGHT/sum(WEIGHT, na.rm = TRUE)) 

# resample
M1 <- 1000

withr::with_seed(seed = 0720, 
                 sample_rows <- sample(x = sirsample1$ITERATION, 
                                       size = M1, 
                                       replace = TRUE, 
                                       prob = sirsample1$prob)
)

sirresample1 <- sirsample1[sample_rows, ]

map_lgl(sirresample1, anyNA)

# resample method 2 -------------------------------------------------------

M2 <- 1000

sirinput <- glue("{modelDir}/{sirrunno}/{sirrunno}.ext")
siroutput <- glue("{modelDir}/{sirrunno}/{sirrunno}-rs.ext")

system(glue('/opt/NONMEM/nm75/util/table_resample {sirinput} {siroutput} s {M2} 0720'))

sirresample2 <- read.table(siroutput, skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0)

names(sirresample2) <- gsub("\\.", "\\", names(sirresample2))


# dOFV plot (two method comparison) ---------------------------------------

sirresample1 <- sirresample1 %>% mutate(df = round(mean(dOFV), digits = 2))
sirresample2 <- sirresample2 %>% mutate(df = round(mean(dOFV), digits = 2))

ggplot()+
  stat_ecdf(data = sirresample1, aes(x = dOFV), color = "red")+
  stat_ecdf(data = sirresample2, aes(x = dOFV), color = "blue")+
  geom_text(data = distinct(sirresample1, df), aes(x = 20, y = 0.25, label = glue("SIR df using method 1: {df}")), color = "red")+
  geom_text(data = distinct(sirresample2, df), aes(x = 22.5, y = 0.25, label = glue("SIR df using method 2: {df}")), color = "blue")+
  ylab("Cumulative probablity")+
  theme_bw()+
  coord_flip()


# dOFV final --------------------------------------------------------------

dofv_dt <- bind_rows(sirsample1 %>% dplyr::select(-WEIGHT, -prob) %>% mutate(df = round(mean(dOFV), digits = 2), type = "Proposal"), 
                     sirresample2 %>% mutate(type = "SIR"))

ggplot()+
  stat_ecdf(data = dofv_dt, aes(x = dOFV, group = type, color = type))+
  stat_function(fun = pchisq, args = list(df = nparam), color = "gray20", linetype = 2)+
  geom_text(data = distinct(dofv_dt, df, .keep_all = TRUE), 
            aes(x = c(45, 40), y = 0.25, label = glue("Estimated df: {df}"), color = type))+
  geom_text(aes(x = 42.5, y = 0.25), label = glue("Theoretical Chi-Squared Distribution with {nparam} df"), color = "gray20")+
  theme_bw() + 
  ylab("Cumulative probablity")+
  coord_flip()+
  theme(legend.title = element_blank(), 
        legend.position = "bottom")
  

# ci plot -----------------------------------------------------------------

# SIR 95% CI
sirci <- sirresample2 %>% 
  dplyr::select(starts_with("THETA"), 
                starts_with("OMEGA"), 
                starts_with("SIGMA")) %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "parameter") %>% 
  filter(parameter %in% param_names) %>% 
  rowwise() %>% 
  mutate(sir_median = median(c_across(!parameter)),  
         sir_lower = quantile(c_across(!parameter), 0.025), 
         sir_upper = quantile(c_across(!parameter), 0.975)) %>% 
  ungroup() %>% 
  mutate(type = "SIR") %>% 
  dplyr::select(parameter, sir_median, sir_lower, sir_upper, type) %>% 
  mutate(parameter = fct_inorder(parameter))

# 95% CI based on var-cov matrix (symmetrical)
covci <- mod %>% 
  model_summary() %>% 
  param_estimates() %>% 
  filter(fixed == FALSE) %>% 
  dplyr::select(parameter = parameter_names, estimate, stderr) %>% 
  mutate(final_lower = estimate - 1.96*stderr, 
         final_upper = estimate + 1.96*stderr) %>% 
  mutate(parameter = str_replace_all(parameter, "\\(", "\\")) %>% 
  mutate(parameter = str_replace_all(parameter, "\\)", "\\")) %>% 
  mutate(parameter = str_replace_all(parameter, "\\,", "\\")) %>% 
  mutate(type = "COV") %>% 
  dplyr::select(parameter, final_est = estimate, final_lower, final_upper, type) %>% 
  mutate(parameter = fct_inorder(parameter))

# side to side comparison plot
ggplot()+
  geom_point(data = sirci, aes(x=type, y=sir_median))+
  geom_point(data = covci, aes(x=type, y=final_est))+
  geom_errorbar(data = sirci, aes(x=type, ymin=sir_lower, ymax=sir_upper), width = 0.25)+
  geom_errorbar(data = covci, aes(x=type, ymin=final_lower, ymax=final_upper), width = 0.25)+
  theme_bw()+
  facet_wrap(~parameter, scales = "free")+
  xlab("")+
  ylab("95% CIs")

# spatial trend plot ------------------------------------------------------

nbins <- 10
mmratio = M2/m

bins_sample <- sirsample1 %>% 
  dplyr::select(ITERATION, all_of(param_names)) %>% 
  mutate(across(all_of(param_names), .fns = ~cut_number(., n = 10))) %>% 
  mutate(across(all_of(param_names), .fns = as.integer))

bins_resample <- sirresample2 %>% dplyr::select(ITERATION) %>% left_join(bins_sample)

# sbins <- map(as.list(bins_sample[, names(bins_sample) %in% param_names]), levels) # extract spatial bins

bins_resample <- bins_resample %>% 
  pivot_longer(cols = all_of(param_names), names_to = "parameters", values_to = "bins") %>% 
  group_by(parameters, bins) %>% 
  mutate(prop = round(n()/(m/nbins), digits = 2)) %>% 
  ungroup() %>% 
  distinct(parameters, bins, .keep_all = TRUE) %>% 
  mutate(parameters = fct_inorder(parameters))

ggplot(bins_resample)+
  geom_point(aes(x = bins, y = prop))+
  geom_line(aes(x = bins, y = prop))+
  geom_ribbon(aes(x = bins, ymin = mmratio-1.96*mmratio*(1-mmratio)/nbins, ymax = mmratio+1.96*mmratio*(1-mmratio)/nbins), alpha = 0.5)+
  xlab("Spatial bin of initial samples")+
  ylab("Proportion resampled")+
  scale_x_continuous(limits = c(1, nbins), breaks = seq(1,nbins,1))+
  facet_wrap(~parameters)+
  theme_bw()


# temporal trend plot -----------------------------------------------------




###########################################################################
#################### Sensitivity Analysis #################################
###########################################################################

# dOFV SIRDF sens ---------------------------------------------------------

# we will use NONMEM resampling method for the downstream analysis

sens1_dir <- file.path(modelDir, glue("{sirrunno}-sirdf"))

# resampling using NONMEM
# system(glue('/opt/NONMEM/nm75/util/table_resample {sens1_dir}/{sirrunno}-1/{sirrunno}-1.ext {sens1_dir}/{sirrunno}-1/{sirrunno}-1-rs.ext s {M2} 0720'))
# system(glue('/opt/NONMEM/nm75/util/table_resample {sens1_dir}/{sirrunno}-2/{sirrunno}-2.ext {sens1_dir}/{sirrunno}-2/{sirrunno}-2-rs.ext s {M2} 0720'))
# system(glue('/opt/NONMEM/nm75/util/table_resample {sens1_dir}/{sirrunno}-3/{sirrunno}-3.ext {sens1_dir}/{sirrunno}-3/{sirrunno}-3-rs.ext s {M2} 0720'))
# system(glue('/opt/NONMEM/nm75/util/table_resample {sens1_dir}/{sirrunno}-4/{sirrunno}-4.ext {sens1_dir}/{sirrunno}-4/{sirrunno}-4-rs.ext s {M2} 0720'))

sirsample_sens1_0 <- sirsample1 %>% mutate(SIRDF = 0, df = round(mean(dOFV), digits = 2)) %>% dplyr::select(-prob)

sirsample_sens1_1 <- read.table(glue("{sens1_dir}/{sirrunno}-1/{sirrunno}-1.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(SIRDF = 2, df = round(mean(dOFV), digits = 2))

sirsample_sens1_2 <- read.table(glue("{sens1_dir}/{sirrunno}-2/{sirrunno}-2.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(SIRDF = 4, df = round(mean(dOFV), digits = 2))

sirsample_sens1_3 <- read.table(glue("{sens1_dir}/{sirrunno}-3/{sirrunno}-3.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(SIRDF = 6, df = round(mean(dOFV), digits = 2))

sirsample_sens1_4 <- read.table(glue("{sens1_dir}/{sirrunno}-4/{sirrunno}-4.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(SIRDF = 8, df = round(mean(dOFV), digits = 2))

sirsample_sens1 <- bind_rows(sirsample_sens1_0, 
                             sirsample_sens1_4, 
                             sirsample_sens1_3,
                             sirsample_sens1_2, 
                             sirsample_sens1_1) %>% 
  mutate(SIRDF = as.factor(SIRDF)) %>% 
  mutate(df = glue("Estimated df: {df}"))

ggplot(sirsample_sens1)+
  stat_ecdf(aes(x = dOFV, group = SIRDF, color = SIRDF))+
  stat_function(fun = pchisq, args = list(df = nparam), linetype = 2)+
  geom_text(data = distinct(sirsample_sens1, SIRDF, .keep_all = TRUE), 
            aes(x = seq(20, 36, 4), y = 0.25, label = df, color = SIRDF))+
  geom_text(aes(x = 16, y = 0.25), label = glue("Theoretical Chi-Squared Distribution with {nparam} df"), color = "gray20")+
  theme_bw()+
  ylab("Cumulative probablity")+
  coord_flip()+
  theme(legend.position = "bottom")


# dOFV IACCEPT sens -------------------------------------------------------

# we will use NONMEM resampling method for the downstream analysis

sens3_dir <- file.path(modelDir, glue("{sirrunno}-iaccept"))

# # resampling using NONMEM
# system(glue('/opt/NONMEM/nm75/util/table_resample {sens3_dir}/{sirrunno}-1/{sirrunno}-1.ext {sens3_dir}/{sirrunno}-1/{sirrunno}-1-rs.ext s {M2} 0720'))
# system(glue('/opt/NONMEM/nm75/util/table_resample {sens3_dir}/{sirrunno}-2/{sirrunno}-2.ext {sens3_dir}/{sirrunno}-2/{sirrunno}-2-rs.ext s {M2} 0720'))
# system(glue('/opt/NONMEM/nm75/util/table_resample {sens3_dir}/{sirrunno}-3/{sirrunno}-3.ext {sens3_dir}/{sirrunno}-3/{sirrunno}-3-rs.ext s {M2} 0720'))
# system(glue('/opt/NONMEM/nm75/util/table_resample {sens3_dir}/{sirrunno}-4/{sirrunno}-4.ext {sens3_dir}/{sirrunno}-4/{sirrunno}-4-rs.ext s {M2} 0720'))

sirsample_sens3_0 <- sirsample1 %>% mutate(IACCEPT = 1, df = round(mean(dOFV), digits = 2)) %>% dplyr::select(-prob)

sirsample_sens3_1 <- read.table(glue("{sens3_dir}/{sirrunno}-1/{sirrunno}-1.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(IACCEPT = 0.2, df = round(mean(dOFV), digits = 2))

sirsample_sens3_2 <- read.table(glue("{sens3_dir}/{sirrunno}-2/{sirrunno}-2.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(IACCEPT = 0.4, df = round(mean(dOFV), digits = 2))

sirsample_sens3_3 <- read.table(glue("{sens3_dir}/{sirrunno}-3/{sirrunno}-3.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(IACCEPT = 0.6, df = round(mean(dOFV), digits = 2))

sirsample_sens3_4 <- read.table(glue("{sens3_dir}/{sirrunno}-4/{sirrunno}-4.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(IACCEPT = 0.8, df = round(mean(dOFV), digits = 2))

sirsample_sens3 <- bind_rows(sirsample_sens3_0, 
                             sirsample_sens3_4, 
                             sirsample_sens3_3,
                             sirsample_sens3_2, 
                             sirsample_sens3_1) %>% 
  mutate(IACCEPT = as.factor(IACCEPT)) %>% 
  mutate(df = glue("Estimated df: {df}"))

ggplot(sirsample_sens3)+
  stat_ecdf(aes(x = dOFV, group = IACCEPT, color = IACCEPT))+
  stat_function(fun = pchisq, args = list(df = nparam), linetype = 2)+
  geom_text(data = distinct(sirsample_sens3, IACCEPT, .keep_all = TRUE), 
            aes(x = seq(20, 36, 4), y = 0.25, label = df, color = IACCEPT))+
  geom_text(aes(x = 16, y = 0.25), label = glue("Theoretical Chi-Squared Distribution with {nparam} df"), color = "gray20")+
  theme_bw()+
  ylab("Cumulative probablity")+
  coord_flip()+
  theme(legend.position = "bottom")


# dOFV m/M ratio sens -----------------------------------------------------

# resampling using NONMEM
# taking sirdf = 4 as an example
# five tested ratio: 1,2,5,10,20

sens2_dir <- file.path(modelDir, glue("{sirrunno}-mmratio"))

# resampling using NONMEM
system(glue('/opt/NONMEM/nm75/util/table_resample {sens2_dir}/{sirrunno}-1/{sirrunno}-1.ext {sens2_dir}/{sirrunno}-1/{sirrunno}-1-rs.ext s {M2} -0720'))
system(glue('/opt/NONMEM/nm75/util/table_resample {sens2_dir}/{sirrunno}-2/{sirrunno}-2.ext {sens2_dir}/{sirrunno}-2/{sirrunno}-2-rs.ext s {M2} -0720'))
system(glue('/opt/NONMEM/nm75/util/table_resample {sens2_dir}/{sirrunno}-3/{sirrunno}-3.ext {sens2_dir}/{sirrunno}-3/{sirrunno}-3-rs.ext s {M2} -0720'))
system(glue('/opt/NONMEM/nm75/util/table_resample {sens2_dir}/{sirrunno}-4/{sirrunno}-4.ext {sens2_dir}/{sirrunno}-4/{sirrunno}-4-rs.ext s {M2} -0720'))
system(glue('/opt/NONMEM/nm75/util/table_resample {sens2_dir}/{sirrunno}-5/{sirrunno}-5.ext {sens2_dir}/{sirrunno}-5/{sirrunno}-5-rs.ext s {M2} -0720'))

sirresample_sens2_1 <- read.table(glue("{sens2_dir}/{sirrunno}-1/{sirrunno}-1-rs.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(`m/M ratio` = 1, df = round(mean(dOFV), digits = 2))

sirresample_sens2_2 <- read.table(glue("{sens2_dir}/{sirrunno}-2/{sirrunno}-2-rs.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(`m/M ratio` = 2, df = round(mean(dOFV), digits = 2))

sirresample_sens2_3 <- read.table(glue("{sens2_dir}/{sirrunno}-3/{sirrunno}-3-rs.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(`m/M ratio` = 5, df = round(mean(dOFV), digits = 2))

sirresample_sens2_4 <- read.table(glue("{sens2_dir}/{sirrunno}-4/{sirrunno}-4-rs.ext"), skip = 1, header = TRUE) %>% 
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>% 
  filter(ITERATION > 0) %>% 
  mutate(`m/M ratio` = 10, df = round(mean(dOFV), digits = 2))

sirresample_sens2_5 <- read.table(glue("{sens2_dir}/{sirrunno}-5/{sirrunno}-5-rs.ext"), skip = 1, header = TRUE) %>%
  mutate(dOFV = OBJ - sirsample0[sirsample0$ITERATION == 0,]$OBJ) %>%
  filter(ITERATION > 0) %>%
  mutate(`m/M ratio` = 20, df = round(mean(dOFV), digits = 2))

sirresample_sens2 <- bind_rows(sirresample_sens2_1, 
                               sirresample_sens2_2, 
                               sirresample_sens2_3, 
                               sirresample_sens2_4, 
                               sirresample_sens2_5) %>% 
  mutate(`m/M ratio` = as.factor(`m/M ratio`)) %>% 
  mutate(df = glue("Estimated df: {df}"))

ggplot(sirresample_sens2)+
  stat_ecdf(aes(x = dOFV, group = `m/M ratio`, color = `m/M ratio`))+
  stat_function(fun = pchisq, args = list(df = nparam), linetype = 2)+
  geom_text(data = distinct(sirresample_sens2, `m/M ratio`, .keep_all = TRUE), 
            aes(x = seq(29.6, 20, -2.4), y = 0.25, label = df, color = `m/M ratio`))+
  geom_text(aes(x = 32, y = 0.25), label = glue("Theoretical Chi-Squared Distribution with {nparam} df"), color = "gray20")+
  theme_bw()+
  coord_flip()


















